### ISSUE TITLE
Proof-of-Work miners can opt-out of paying incentive rewards to nodes.

### ISSUE THREAD

**Issue by ghost** [xCoreDev/vcash#2]
https://github.com/vdotcash/vcash/commit/b67410d9cfc97c3e3f7a7ff36eeaac3a0f3705a8

**Comment by vdotcash** [comment]
https://explorer.vchain.info/tx/2394702af1d96ab3c9eb0f9ae84e2a02651842c2e3547f0e21bdfce67260b3fd

**Comment by ghost** [comment]
![img_0080](https://cloud.githubusercontent.com/assets/24429359/21034969/d5064b54-bd89-11e6-94d3-84dc335d47e9.PNG)

**Comment by hclivess** [comment]
Good job, guys. Thank you.

**Comment by xCoreDev** [comment]
@vdotcash Be my guest & fix it, that's your code, isn't it ?
It seems you want to talk, so please tell us why you are spamming the network with your alert key ?
Why are you tweeting about your own flaw so quickly `https://twitter.com/vdotcash/status/807051099307905029` & not following the the classic way to disclose a flaw ?
Why close and reopen v.cash website / @vdotcash twitter / hardcoded bootstrap nodes so many time ?
Why did you wipe the forum ?
I don't pretend to be the "lead dev" like many are actually saying. I'm just here to not abandon everyone and contribute by keeping my part of the network alive & healthy (see: `https://forum.vcash.info/d/7-statement-regarding-recent-events`). We do need more decentralization, so I would like to invite all those who wish to contribute to jump on slack or freenode. There's only 24h in a day, and so much to do.
To get back on-topic w/ the flaw, I suggest a mandatory upgrade to stop the alert spamming. Once that part done, start banning peers w/ empty blocks (it will required debug sessions on the testnet).
Now we need to reach a consensus w/ users, pools, & exchanges, to deploy this upgrade.
Have a good day/night.

**Comment by ocminer** [comment]
Just for historical reasons: suprnova never mined a block without incentive, you can check the block explorer(s)

**Comment by ghost** [comment]
@ocminer Instead suprnova just forked off the network (cheap VPS could not reorg). The other pools except xCore's kept working just fine because he too run cheap VPS and failed to reorg.

**Comment by vdotcash** [comment]
xCore, no this is your code, you have taken the lead developer position publically through a takeover. If you want the ZeroDays fixed it's your job. Good luck with the project.

**Comment by ocminer** [comment]
After the poolnode got banned it had no other possibility but fork off...  Even while it had a large portion of the network at that time which should prevent it from forking automatically...

**Comment by ghost** [comment]
@ocminer You are so desperate. How do you ban a pool? You cannot.

**Comment by ghost** [comment]
xCore, no this is your code, you have taken the lead developer position publically through a takeover. If you want the ZeroDays fixed it's your job. Good luck with the project.

**Comment by betmoar** [comment]
Takeover? You disgraced the community when your DID did a takeover. You are acting like a liberal crybaby JC.

**Comment by hclivess** [comment]
It's Christmas, let's all get together and code!

**Comment by tloriato** [comment]
@vdotcash Hey Julian Cain, how are things going? Don't drink and drive again, ok? Cheers~

**Comment by xaur** [comment]
Shouldn't other nodes validate that blocks contain incentive rewards and reject blocks that don't?

_edit: removed off-topic_

**Comment by jimlite** [comment]
JC,
I am seriously willing to hear your side of the story and what you want for the future of Vcash. You know where to find me on IRC and I even tried your old bitmessage. Honestly the community is in limbo because we don't know what you want for the future of the coin. xCore is just doing what is needed to keep the network going until we know your wishes. Do you want to dissapear like Satoshi and let xCore and others take over like Gavin and GMaxwell did for Satoshi? Or do you want to continue to be sole and lead dev of Vcash, code, communicate, and show the world the potential of this awesome coin? The problem is no one knows what you want right now. So please communicate that to me or xCore and myself as well as the long term followers will all try and respect that, regardless of all the FUD and anger coming from the community. Personally I highly respect your past work and acomplishments, but as I have always said communitcation and PR are very important in crypto. Please let one of us know what you really want, and we will try to make that happen, no more games.

**Comment by ghost** [comment]
https://youtu.be/ic-CMlZdQ0E

**Comment by jimlite** [comment]
https://youtu.be/Ils9GXqU03c?t=35

**Comment by tloriato** [comment]
Thanks for your support 😎

**Comment by pingofchaos** [comment]
![68d4628b93](https://cloud.githubusercontent.com/assets/20494277/21072893/c9d59f6c-bed0-11e6-90bb-4e1a2a963c4d.gif)

**Comment by GabrielAugustoTI** [comment]
Fuck you JC!

**Comment by TheTaker666** [comment]
Better watch over your children JC

**Comment by TopoTorres** [comment]
JC, no one betrayed you, we're all here waiting for your response!
**You're a genius and we love you.**
